### ISSUE TITLE
Test install by pip3

### ISSUE THREAD

**Issue by wlorenzetti** [g3w-suite/g3w-admin-sentry-monitor#1]
Inside my development environment I try to install:

1. I make a new folter with name plugins parallel to g3w-admin directory
2. I clone the g3w-admin-sentry-monitor inside it
3. Try to install with: `pip install -e ./g3w-admin-sentry-monitor`

But I obtain the following error:
```
Obtaining file:///home/walter/PycharmProjects/g3w_suite_qgis_api/plugins/g3w-admin-sentry-monitor
  Installing build dependencies ... done
  Checking if build backend supports build_editable ... done
ERROR: Project file:///home/walter/PycharmProjects/g3w_suite_qgis_api/plugins/g3w-admin-sentry-monitor has a 'pyproject.toml' and its build backend is missing the 'build_editable' hook. Since it does not have a 'setup.py' nor a 'setup.cfg', it cannot be installed in editable mode. Consider using a build backend that supports PEP 660.
```

**Comment by Raruto** [comment]
What is your current `pip` version?

Currently, for a g3w-suite-docker@v3.5 (Ubuntu Jammy) instance, I get the following:

```sh
pip3 --version
pip 22.0.2 from /usr/lib/python3/dist-packages/pip (python 3.10)

# pip --version
# pip 22.0.2 from /usr/lib/python3/dist-packages/pip (python 3.10)
```

Perhaps unrelated to this specific issue, but for make it work I also needed to add the following `export` in my development environment:

```sh
# g3w-suite-docker/scripts/docker-entrypoint-dev.sh

# hotfix for Ubuntu Jammy: https://github.com/pypa/setuptools/issues/3269#issuecomment-1254507377
export DEB_PYTHON_INSTALL_LAYOUT=deb_system

# And then install the python package
pip3 install...
```

**Comment by wlorenzetti** [comment]
Currently I'm on Ubuntu 22.04 (Jammy) and after update pip to version 22.3.1 and after set env variable DEB_PYTHON_INSTALL_LAYOUT, the installation went well!
